package com.csumb.cst363;

/*
 * This class is used to transfer data to/from doctor templates
 *  for registering new doctor and updating doctor profile.
 */
public class Doctor {

	private int doctorId;   // unique id generated by database.
	private String doctorSSN;
	private String doctorFirstName;
	private String doctorLastName;
	private String specialty;
	private String practiceSinceYear; // yyyy  The year doctor started in practice.

	public int getDoctorId() {
		return doctorId;
	}

	public void setDoctorId(int doctorId) {
		this.doctorId = doctorId;
	}

	public String getDoctorSSN() {
		return doctorSSN;
	}

	public void setDoctorSSN(String doctorSSN) {
		this.doctorSSN = doctorSSN;
	}

	public String getDoctorFirstName() {
		return doctorFirstName;
	}

	public void setDoctorFirstName(String doctorFirstName) {
		this.doctorFirstName = doctorFirstName;
	}

	public String getDoctorLastName() {
		return doctorLastName;
	}

	public void setDoctorLastName(String doctorLastName) {
		this.doctorLastName = doctorLastName;
	}

	public String getSpecialty() {
		return specialty;
	}

	public void setSpecialty(String speciality) {
		this.specialty = speciality;
	}

	public String getPracticeSinceYear() {
		return practiceSinceYear;
	}

	public void setPracticeSinceYear(String practiceSinceYear) {
		this.practiceSinceYear = practiceSinceYear;
	}

	@Override
	public String toString() {
		return "Doctor ["
			+ "doctorId=" + doctorId
			+ ", doctorSSN=" + doctorSSN
			+ ", doctorFirstName=" + doctorFirstName
			+ ", doctorLastName=" + doctorLastName
			+ ", speciality=" + specialty
			+ ", practiceSinceYear=" + practiceSinceYear
			+ "]";
	}
}
