package com.csumb.cst363;

/*
 * This class is used to transfer data to/from patient templates.
 */
public class Patient {

	private String patientId;  // unique id generated by database.
	private String primaryDoctorId;
	private String patientSSN;
	private String patientFirstName;
	private String patientLastName;
	private String patientBirthdate;  // yyyy-mm-dd
	private String patientState;
	private String patientZip;
	private String patientCity;
	private String patientStreet;

	// following fields are data about primary doctor
	private String primaryFirstName;
	private String primaryLastName;
	private String specialty;
	private String practiceSinceYear;

	public String getPatientId() {
		return patientId;
	}

	public void setPatientId(String patientId) {
		this.patientId = patientId;
	}

	public String getPrimaryDoctorId() {
		return primaryDoctorId;
	}

	public void setPrimaryDoctorId(String primaryDoctorId) {
		this.primaryDoctorId = primaryDoctorId;
	}

	public String getPatientSSN() {
		return patientSSN;
	}

	public void setPatientSSN(String patientSSN) {
		this.patientSSN = patientSSN;
	}

	public String getPatientFirstName() {
		return patientFirstName;
	}

	public void setPatientFirstName(String patientFirstName) {
		this.patientFirstName = patientFirstName;
	}

	public String getPatientLastName() {
		return patientLastName;
	}

	public void setPatientLastName(String patientLastName) {
		this.patientLastName = patientLastName;
	}

	public String getPatientBirthdate() {
		return patientBirthdate;
	}

	public void setPatientBirthdate(String patientBirthdate) {
		this.patientBirthdate = patientBirthdate;
	}

	public String getPatientState() {
		return patientState;
	}

	public void setPatientState(String patientState) {
		this.patientState = patientState;
	}

	public String getPatientZip() {
		return patientZip;
	}

	public void setPatientZip(String patientZip) {
		this.patientZip = patientZip;
	}

	public String getPatientCity() {
		return patientCity;
	}

	public void setPatientCity(String patientCity) {
		this.patientCity = patientCity;
	}

	public String getPatientStreet() {
		return patientStreet;
	}

	public void setPatientStreet(String patientStreet) {
		this.patientStreet = patientStreet;
	}

	public String getPrimaryFirstName() {
		return primaryFirstName;
	}

	public void setPrimaryFirstName(String primaryFirstName) {
		this.primaryFirstName = primaryFirstName;
	}

	public String getPrimaryLastName() {
		return primaryLastName;
	}

	public void setPrimaryLastName(String primaryLastName) {
		this.primaryLastName = primaryLastName;
	}

	public String getSpecialty() {
		return specialty;
	}

	public void setSpecialty(String specialty) {
		this.specialty = specialty;
	}

	public String getPracticeSinceYear() {
		return practiceSinceYear;
	}

	public void setPracticeSinceYear(String practiceSinceYear) {
		this.practiceSinceYear = practiceSinceYear;
	}

	@Override
	public String toString() {
		return "Patient ["
			+ "patientId=" + patientId
			+ ", primaryDoctorId=" + primaryDoctorId
			+ ", patientSSN=" + patientSSN
			+ ", patientFirstName=" + patientFirstName
			+ ", patientLastName=" + patientLastName
			+ ", patientBirthdate=" + patientBirthdate
			+ ", patientState=" + patientState
			+ ", patientZip=" + patientZip
			+ ", patientCity=" + patientCity
			+ ", patientStreet=" + patientStreet
			+ ", primaryFirstName=" + primaryFirstName
			+ ", primaryLastName=" + primaryLastName
			+ ", specialty=" + specialty
			+ ", practiceSinceYear=" + practiceSinceYear
			+ "]";
	}
}
